steps:
  - id: build
    name: 'gcr.io/kaniko-project/executor:v0.16.0'
    args:
      - --dockerfile=./deployments/production/Dockerfile
      - --destination=gcr.io/${PROJECT_ID}/${_APP_NAME}
      - --cache=true
      - --cache-ttl=6h
  - id: "deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta run deploy ${_APP_NAME} \
          --platform managed \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --image gcr.io/${PROJECT_ID}/${_APP_NAME} \
          --add-cloudsql-instances ${_INSTANCE_CONNECTION_NAME} \
          --set-env-vars INSTANCE-CONNECTION-NAME="${_INSTANCE_CONNECTION_NAME}"
substitutions:
  _APP_NAME: places-strapi-app
  _INSTANCE_CONNECTION_NAME: 'azoom-k-gotou:asia-northeast1:places-strapi-db'